lecture3/hello/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index, name = 'index'),
    path("james", views.james, name = 'james'),
    path('<str:name>', views.greet, name = 'greet')
]

lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('newyear/', include('newyear.urls')),
    path('tasks/', include('tasks.urls'))
]

lecture3/newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name = 'index')
]

lecture3/tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'
urlpatterns = [
    path("add", views.add, name = 'add'),
    path("", views.index, name = 'index')

]

lecture3/hello/models.py
from django.db import models

# Create your models here.

lecture3/newyear/models.py
from django.db import models

# Create your models here.

lecture3/tasks/models.py
from django.db import models

# Create your models here.

lecture3/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render
# Create your views here.

def index(request):
    return HttpResponse("Hello, Kaku!") 


def james(request):
    return HttpResponse('Hello James')

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

lecture3/newyear/views.py
import datetime
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    now = datetime.datetime.now()
    return render(request, 'newyear/index.html', {
        "newyear": now.month ==12 and now.day ==30
    })

lecture3/tasks/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


# Create your views here.
class NewTaskForm(forms.Form):
    task = forms.CharField(label = 'New Task')


# listing the tasks

def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })


def add(request):
    #check for both server and client side validation
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"].append(task)
            request.session.modified = True  # Ensure the session is saved after modification
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, 'tasks/add.html', {"form": form})


    return render(request, 'tasks/add.html', {
        "form": NewTaskForm()
    })

lecture3/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello</title>
</head>
<body>
    <h1>Hello, {{ name }}! </h1>
    <h2>Thank You</h2>
</body>
</html>

lecture3/newyear/templates/newyear/index.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Year</title>
    <link rel="stylesheet" href="{% static 'newyear/styles.css' %}">
</head>
<body>
    {% if newyear %}
        <h1>YES</h1>
    {% else %}
        <h1>NO</h1>
    {% endif %}
</body>
</html>

lecture3/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block boby %}
    <H1> Add New Task </H1>
    <form action="{% url 'tasks:add' %}" method ="post">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>
    <a href="{% url 'tasks:index' %}"> view tasks </a>

{% endblock %}

lecture3/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block boby %}


    <h1>TASKS</h1>
    <ul>
        {% for task in tasks %}
                <li>{{ task }}</li>
        {% empty %}
            <li> No task.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}"> Add a New Task </a>


{% endblock %}

lecture3/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Tasks </title>
</head>
<body>
    {% block boby %}
    
    {% endblock%}
</body>
</html>